package dao; import java.sql.*; import model.Account; import util.db;
public class AccountDAO {
    private void print(ResultSet rs)throws Exception{System.out.println(rs.getInt("id")+" | "+rs.getString("holder_name")+" | "+rs.getString("email")+" | "+rs.getString("account_type")+" | Rs."+rs.getDouble("balance")+" | "+rs.getString("open_date"));}
    public boolean add(Account a){try{PreparedStatement ps=db.getConnection().prepareStatement("INSERT INTO accounts(holder_name,email,account_type,balance,open_date)VALUES(?,?,?,?,?)");ps.setString(1,a.getHolderName());ps.setString(2,a.getEmail());ps.setString(3,a.getAccountType());ps.setDouble(4,a.getBalance());ps.setString(5,a.getOpenDate());return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void viewAll(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM accounts").executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("No accounts.");}catch(Exception e){}}
    public void searchById(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM accounts WHERE id=?");ps.setInt(1,id);ResultSet rs=ps.executeQuery();if(rs.next())print(rs);else System.out.println("Not found.");}catch(Exception e){}}
    public boolean deposit(int id,double amt){try{PreparedStatement ps=db.getConnection().prepareStatement("UPDATE accounts SET balance=balance+? WHERE id=?");ps.setDouble(1,amt);ps.setInt(2,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public boolean withdraw(int id,double amt){try{PreparedStatement ps=db.getConnection().prepareStatement("UPDATE accounts SET balance=balance-? WHERE id=? AND balance>=?");ps.setDouble(1,amt);ps.setInt(2,id);ps.setDouble(3,amt);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public boolean delete(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("DELETE FROM accounts WHERE id=?");ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void count(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT COUNT(*) FROM accounts").executeQuery();if(rs.next())System.out.println("Total Accounts: "+rs.getInt(1));}catch(Exception e){}}
    public void highestBalance(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM accounts ORDER BY balance DESC LIMIT 1").executeQuery();if(rs.next()){System.out.println("Highest Balance:");print(rs);}}catch(Exception e){}}
    public void sortByBalance(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM accounts ORDER BY balance DESC").executeQuery();while(rs.next())print(rs);}catch(Exception e){}}
    public void accountTypeReport(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT account_type,COUNT(*) as cnt,SUM(balance) as total FROM accounts GROUP BY account_type").executeQuery();System.out.println("Type | Count | Total Balance");while(rs.next())System.out.println(rs.getString("account_type")+" | "+rs.getInt("cnt")+" | Rs."+rs.getDouble("total"));}catch(Exception e){}}
}
